### ISSUE TITLE
[fxos] Bring bzdeck's performance in parity with Bugzilla lite

### ISSUE THREAD

**Issue by nt1m** [bzdeck/bzdeck#306]
Bugzilla lite runs much faster than bzdeck on Firefox OS. It also looks better.

**Comment by kyoshino** [comment]
Performance and mobile optimization is planned for [Beta 14](https://github.com/bzdeck/bzdeck/milestones/Beta%2014). But it may be delayed because my Flame phone used for testing was stolen yesterday  :crying_cat_face:


We could do better anyway, though it's difficult to compare BzDeck with Bugzilla Lite. Bugzilla Lite has been built exclusively for Firefox OS, while BzDeck is a cross platform app.

**Comment by kyoshino** [comment]
Marking this issue duplicate of #290.
