### ISSUE TITLE
Set a User Agent when making requests to Bugzilla's API

### ISSUE THREAD

**Issue by edmorley** [bzdeck/bzdeck#393]
It's best practice to set an informative User Agent when making requests to an external API, and helps those maintaining the API track the sources of inefficient queries/heavy load :-)

**Comment by kyoshino** [comment]
👍 The `User-Agent` header should be able to be set since [Firefox 43](https://bugzilla.mozilla.org/show_bug.cgi?id=1188932).

**Comment by kyoshino** [comment]
Depends on https://github.com/bugzilla/bugzilla/pull/30

**Comment by kyoshino** [comment]
This is now live on production!

**Comment by edmorley** [comment]
Many thanks! :-)

**Comment by kyoshino** [comment]
Regarding inefficient queries: BzDeck and perhaps other Bugzilla API clients are sending too many queries because of [Bug 994896](https://bugzilla.mozilla.org/show_bug.cgi?id=994896) and [Bug 1169040](https://bugzilla.mozilla.org/show_bug.cgi?id=1169040), as mentioned in [this Wiki page](https://github.com/bzdeck/bzdeck/wiki/Bugzilla-API-Enhancements). Once those bugs are fixed, the number of queries will be drastically decreased.
